name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Cypress tests
      id: cypress-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Cypress tests
        setup-command: npm install
        command: npm run test-with-server
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CYPRESS-TESTS_RESULTS: "${{steps.cypress-tests.outputs.result}}"
      with:
        runners: cypress-tests
