entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik.yaml"

tls:
  certificates:
    - certFile: "/etc/traefik/certificates/cert.pem"
      keyFile: "/etc/traefik/certificates/key.pem"

api:
  dashboard: true

http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
  routers:
    web-to-secure:
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
